#!/usr/bin/env sh

# Uninstallation script.
# - takes one argument: `-f` (`--force`) or `-i` (`--interactive`) which is passed to the cleaning script
# - idempotent


# Get directory of script, resolving symbolic links.
# (see: https://stackoverflow.com/questions/29832037)
# (see: https://stackoverflow.com/questions/10412162)
base_dir=$(

  base_dir=${0}

  while [ -L "${base_dir}" ]; do

    cd "${base_dir%/*}"
    base_dir=$(readlink "${base_dir}")

  done

  cd "${base_dir%/*}"
  pwd -P

)


# CLEAN

# Check for run conditions.
if [ "$1" = "--force" -o "$1" = "-f" ]; then

  [ -r "${base_dir}"/script/clean.sh ] && source "${base_dir}"/script/clean.sh -f

elif [ "$1" = "--interactive" -o "$1" = "-i" ]; then

  [ -r "${base_dir}"/script/clean.sh ] && source "${base_dir}"/script/clean.sh -i

else

  read -r -p "This may overwrite existing files. Are you sure? (y/n) " -n 1
  echo ""
  if [ $( expr $REPLY : '[yY]$' ) -eq 1  ]; then
    
    [ -r "${base_dir}"/script/clean.sh ] && source "${base_dir}"/script/clean.sh -f
    
  fi

fi


# Clean up.
unset base_dir